### ISSUE TITLE
BetterButtonLink attempts to open link in CMS

### ISSUE THREAD

**Issue by dhensby** [unclecheese/silverstripe-gridfield-betterbuttons#64]
I'm using the `BetterButtonLink` to give the CMS user access to preview a PDF, however, when this happens it tries to open the PDF in the CMS admin via an AJAX request which results in encoded text being displayed.

Is there a way to force opening in a new tab?

**Comment by Taitava** [comment]
@unclecheese Where can this be configured?

I tried this:

```PHP
$link_action = BetterButtonLink::create($title, $url);
$link_action->setAttribute('target', '_blank');
$fields->push($link_action);
```

It manages to add the `target="_blank"` attribute to the `<a>` element in the CMS, but that doesn't help because the CMS's JavaScript is picking up the `onclick` event of the element and starts to do it's own loading inside the CMS. This could be solved by disabling the JS events completely for this particular `<a>` element somehow, but I don't know how.

My SilverStripe version is 3.4.1. Thanks for help! :)

**Comment by unclecheese** [comment]
Yeah, I think the issue is that the button has class `cms-panel-link` (or something similar), and that gets ajax behaviour attached to it from some core CMS javascript way upstream.

The simple answer to this is to have an option for `->newWindow(true)` that simply removes that class.

**Comment by Taitava** [comment]
Thanks. I will try that and make a PR if I succeed. If I don't, I'll update this message.
